project:
  type: website
  render: 
  -index.qmd
  -FCB/Readme.qmd
  -Arsenal/Arsenal.qmd
  -Analyse/Analyse.qmd

website:
Back-to-top-navigation: True
Page-navigation: True
  title: "Site de Foot"
  site-url: http://Arthur-tena.github.io
  repo-url: https://github.com/Arthur-tena/Arthur-tena.github.io
  # sidebar:
  # left:
  # contents:
  #   - href: Analyse/Analyse.qmd
  #   - href: Arsenal/Arsenal.qmd
  #   - href: FCB/Readme.qmd
  # menu: false
  navbar:
   title: "site de foot"
   background: primary
   search: True
   left:
    -sidebar:FCB
    -sidebar:Arsenal 
    -sidebar:Analyse
  sidebar:
   id: FCB
   title: "FC Barcelone"
   contents: 
   -FCB/Readme.qmd

   id: Arsenal
   title: "Arsenal FC"
   contents: 
   -Arsenal/Arsenal.qmd

   id: Analyse
   title: "Analyse de match"
   contents: 
   -Analyse/Analyse.qmd


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



